name = "zilnet"
main = "worker.js"
compatibility_date = "2026-09-09"

[vars]
DEVELOPER_PASSWORD = "7034"
GITHUB_OWNER = "zilnet-main"
GITHUB_REPO = "Zilnet"
GITHUB_BRANCH = "main"
GITHUB_TOKEN = "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"

[assets]
directory = "./"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "zilnet-db"
database_id = "69f8b11c-1474-4db5-af80-ecd0dc17714d"
