name = "zilnet"
main = "worker.js"
compatibility_date = "2026-09-09"

[assets]
directory = "./"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "zilnet-db"
database_id = "69f8b11c-1474-4db5-af80-ecd0dc17714d"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "zilnet-media"
